### PR TITLE
Travel website

### PR DESCRIPTION
**Pull request by fauziyyanura**
Travel Website mobile view
Responsive travel website mobile view contains images, videos, links and Readme.md file.

### CODE REVIEW

**Comment by Xfarouq** [comment]
Always make sure your link to your website is working in the readme, rectify it and resubmit your project

**Comment by Devsalmasaeed** [comment]
Please note you are to add the loom link in your README file not on description rectify it and resubmit

**Review by Xfarouq — APPROVED** [review]
Hi @fauziyyanura 

Your project is complete! There is nothing else to say other than... it's time to merge it!!!
Congratulations! 🎉

<div style="text-align:center;">
    Remote Collaboration
</div>

### Highlights
- ✅ **Professional Readme**
- ✅ **Good use of Gitflow**
- ✅ **UI looks like the Figma design**
- ✅ **Good use of HTML semantics**
- ✅ **Professional commit messages**
- ✅ **Professional PR title**
- ✅ **Professional PR description**

### Optional Suggestions

- Always make sure to add title attribute to your images for best practices
- Invert the images in your second section i.e. images inside your cards
Every comment with the `[OPTIONAL]` prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding! 👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.  
Please, remember to tag me in your question so I can receive the notification._

**Comment by fauziyyanura** [comment]
Noted with thanks 🥳🎉

**Pull request merged**
